public enum Symbol {
  FCERC, DCERC, FRECT, DRECT, RECT, CERC,
  NRB, OP, IDENT, VARIA, CONST, COLOR, NOT,
  IF, THEN, ELSE, BEGIN, END, LPAR, RPAR, COMMA, SEMICOLON,
	GT, LT, GTEQ, LTEQ, ASSIGN, EQ;
}
